name: hashicorp-go-azure-sdk-index

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'HashiCorp go-azure-sdk version (e.g., v4.0.0). Leave empty to use latest.'
        required: false
        type: string
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write
  pull-requests: read


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check go-azure-sdk version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            # Use manually provided version
            latest="${{ github.event.inputs.version }}"
            echo "Using manually provided version: $latest"
          else
            # Fetch latest version from repository
            latest=$(gh api repos/hashicorp/go-azure-sdk/tags |\
            jq -r '.[].name' | \
            grep -E '^[vV]?[0-9]+\.[0-9]+\.[0-9]+$' | \
            sort -V | \
            tail -n1)
            echo "Found latest version: $latest"
          fi
          echo VERSION=$latest >> $GITHUB_ENV
          
          # Check if current repo already has this tag
          tag_exists=$(gh api repos/${{ github.repository }}/git/refs/tags/$latest --silent && echo "true" || echo "")
          if [ -n "$tag_exists" ]; then
            echo "Tag $latest already exists in this repository. Stopping workflow."
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
            exit 0
          fi

      - name: Checkout code
        if: ${{ env.TAG_EXISTS != 'true' }}
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      - name: Set up Go
        if: ${{ env.TAG_EXISTS != 'true' }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0

      - name: Install gophon
        if: ${{ env.TAG_EXISTS != 'true' }}
        run: go install github.com/lonegunmanb/gophon@latest

      - name: Checkout go-azure-sdk
        if: ${{ env.TAG_EXISTS != 'true' }}
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
        with:
          repository: hashicorp/go-azure-sdk
          ref: ${{ env.VERSION }}
          path: ./tmp/go-azure-sdk

      - name: Clean previous index files
        if: ${{ env.TAG_EXISTS != 'true' }}
        run: rm -rf ./index

      - name: Pre-warm cache
        if: ${{ env.TAG_EXISTS != 'true' }}
        run: cd tmp/go-azure-sdk && go mod download

      - name: Generate index
        if: ${{ env.TAG_EXISTS != 'true' }}
        env:
          GOPHON_CPU_LIMIT: "50"
        run: |
          cd ./tmp/go-azure-sdk
          gophon -pkg=sdk -base=github.com/hashicorp/go-azure-sdk -dest=../../index
          gophon -pkg=resource-manager -base=github.com/hashicorp/go-azure-sdk -dest=../../index
          gophon -pkg=microsoft-graph -base=github.com/hashicorp/go-azure-sdk -dest=../../index

      - name: Commit and push index files
        if: ${{ env.TAG_EXISTS != 'true' }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./index
          git commit -m "Update index files for go-azure-sdk ${{ env.VERSION }}"
          git push origin main
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}